[package]
name = "tuble"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["HtmlSelectElement"] }
yew = { version = "0.20", features = ["csr"] }
